//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace var5lab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int ID { get; set; }
        public long Number { get; set; }
        public string Holder { get; set; }
        public int? Month { get; set; }
        public int? Year { get; set; }
        public int? CVV { get; set; }
        public Card(int id, Int64 number, string holder, int? month,int? year, int? cvv)
        {
            ID = id;
            Number = number;
            Holder = holder;
            Month = month;
            Year = year;
            CVV = cvv;

        }
    }
}
