//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace var5lab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash
    {
        public int ID { get; set; }
        public int Surrender { get; set; }
        public Cash(int id, int surrender)
        {
            ID = id;
            Surrender = surrender;
        }
    }
}
